import type { WooProduct, WooCartItem, WooStoreOrderItem } from "@/lib/woocommerce/types";

// ── Minimal WooProduct fixture ────────────────────────────────────────────────
export const makeProduct = (overrides: Partial<WooProduct> = {}): WooProduct => ({
  id: 1,
  name: "Test Perfume",
  slug: "test-perfume",
  type: "simple",
  description: "<p>A great scent</p>",
  short_description: "",
  sku: "TP-001",
  permalink: "https://example.com/product/test-perfume",
  prices: {
    price: "2999",
    regular_price: "3999",
    sale_price: "2999",
    currency_code: "USD",
    currency_symbol: "$",
    currency_minor_unit: 2,
    currency_decimal_separator: ".",
    currency_thousand_separator: ",",
    currency_prefix: "$",
    currency_suffix: "",
    price_range: null,
  },
  images: [
    {
      id: 10,
      src: "https://example.com/image.jpg",
      thumbnail: "https://example.com/image-thumb.jpg",
      srcset: "",
      sizes: "",
      name: "test-perfume",
      alt: "Test Perfume",
    },
  ],
  categories: [{ id: 5, name: "Fragrance", slug: "fragrance" }],
  tags: [],
  attributes: [],
  variations: [],
  has_options: false,
  is_purchasable: true,
  is_in_stock: true,
  on_sale: true,
  average_rating: "4.5",
  review_count: 12,
  low_stock_remaining: null,
  add_to_cart: {
    text: "Add to cart",
    description: "",
    url: "",
    minimum: 1,
    maximum: 99,
    multiple_of: 1,
  },
  ...overrides,
});

// ── Minimal WooCartItem fixture ───────────────────────────────────────────────
export const makeCartItem = (overrides: Partial<WooCartItem> = {}): WooCartItem => ({
  key: "abc123",
  id: 1,
  quantity: 2,
  quantity_limits: { minimum: 1, maximum: 99, multiple_of: 1, editable: true },
  name: "Test Perfume",
  short_description: "",
  description: "",
  sku: "TP-001",
  images: [],
  variation: [],
  prices: {
    price: "2999",
    regular_price: "3999",
    sale_price: "2999",
    currency_code: "USD",
    currency_symbol: "$",
    currency_minor_unit: 2,
    currency_prefix: "$",
    currency_suffix: "",
  },
  totals: {
    line_subtotal: "5998",
    line_subtotal_tax: "0",
    line_total: "5998",
    line_total_tax: "0",
    currency_code: "USD",
    currency_symbol: "$",
    currency_minor_unit: 2,
    currency_prefix: "$",
    currency_suffix: "",
  },
  ...overrides,
});

// ── Minimal WooStoreOrderItem fixture ─────────────────────────────────────────
export const makeOrderItem = (
  overrides: Partial<WooStoreOrderItem> = {}
): WooStoreOrderItem => ({
  key: "order-item-abc",
  id: 1,
  quantity: 1,
  name: "Test Perfume",
  short_description: "",
  description: "",
  sku: "TP-001",
  images: [],
  variation: [],
  prices: {
    price: "2999",
    regular_price: "2999",
    sale_price: "",
    currency_code: "USD",
    currency_symbol: "$",
    currency_minor_unit: 2,
    currency_prefix: "$",
    currency_suffix: "",
  },
  totals: {
    line_subtotal: "2999",
    line_subtotal_tax: "0",
    line_total: "2999",
    line_total_tax: "0",
    currency_code: "USD",
    currency_symbol: "$",
    currency_minor_unit: 2,
    currency_prefix: "$",
    currency_suffix: "",
  },
  ...overrides,
});
